[manifest]
version = "1.0.0"
dump_lua = true
priority = 214748364



# Display astral pin preview when selecting hand
# CardArea:parse_highlighted()
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
match_indent = true
position = 'after'
pattern = '''
update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
'''
payload = '''
if G.GAME.Astral_pins then
    if text ~= G.aij_cur_astral_hand then
        All_in_Jest.astral_visuals(text, 'no_remove')
    end
    if text then
        G.aij_cur_astral_hand = text
    end
end
'''
# Synchronize Astral pins right before scoring
# G.FUNC.evaluate_play()
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
position = 'after'
pattern = 'local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)'
payload = '''
if G.GAME.Astral_pins and G.aij_cur_astral_hand ~= text then
    if G.aij_astral_pin_area then
        for _, v in pairs(G.aij_astral_pin_area.cards) do
            v:remove()
        end
    end
    All_in_Jest.astral_visuals(text, 'no_remove')
    G.aij_cur_astral_hand = text
end
'''

# Adds Astral pin area to calculation pipeline
# SMODS.get_card_areas()
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
match_indent = true
position = 'after'
pattern = '''
-- TARGET: add your own CardAreas for joker evaluation
'''
payload = '''
table.insert(t, 1, G.aij_astral_pin_area)
'''

# Remove astral pins
# CardArea:parse_highlighted()
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
match_indent = true
position = 'after'
pattern = '''
local text,disp_text,poker_hands = G.FUNCS.get_poker_hand_info(self.highlighted)
'''
payload = '''
if G.GAME.Astral_pins and text ~= G.aij_cur_astral_hand then
    All_in_Jest.astral_visuals(text, 'only_remove', All_in_Jest.old_colours or nil, true)      
    if text == "NULL" then
        G.aij_cur_astral_hand = nil
    end
    if G.aij_astral_pin_area then
        for _, v in pairs(G.aij_astral_pin_area.cards) do
            v:remove()
        end
    end
end
'''
# Force astral pins to dissolve at end of round
# end_round()
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '-- TARGET: main end_of_round evaluation'
position = 'after'
match_indent = true
payload = '''
for _, v in ipairs(G.aij_astral_pin_area.cards) do
    v:start_dissolve()
end
'''

# Force astral pins to dissolve after hand is played
# evaluate_play()
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '-- TARGET: effects after hand evaluation'
position = 'after'
match_indent = true
payload = '''
for _, v in ipairs(G.aij_astral_pin_area.cards) do
    if not v.ability.no_auto_destroy then
        G.E_MANAGER:add_event(Event({
            trigger = 'immediate',
            func = function()
                v:start_dissolve()
                return true
            end
        }))
    end
end
'''

# Force astral pins to dissolve when discarding
# G.FUNCS.discard_cards_from_highlighted()
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '-- TARGET: pre_discard'
position = 'after'
match_indent = true
payload = '''
if not hook then
    All_in_Jest.astral_visuals(text, 'only_remove', All_in_Jest.old_colours or nil, true)      
    G.aij_cur_astral_hand = nil
    if G.aij_astral_pin_area then
        for _, v in ipairs(G.aij_astral_pin_area.cards) do
            v:start_dissolve()
        end
    end
end
'''

# This is so astral pins info queue can work
# generate_card_ui()
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
   end'''
position = 'at'
payload = '''localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
   elseif _c.set == "aij_astral" then
	 	localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
	 end
'''
match_indent = true


# Adds card area for astral pins, and loading astral pins
# Game:start_run()
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.discard = CardArea("
position = "before"
match_indent = true
payload = '''
self.aij_astral_pin_area = self.aij_astral_pin_area or CardArea(
	self.ROOM.T.x*5.2, self.ROOM.T.h/4,
	3.35 * self.CARD_W,
	0.95 * self.CARD_H,
	{ card_limit = 3, type = 'title', highlight_limit = 0, collection = true }
)

if not saveTable then
    if G.GAME.Astral_pins then
        G.GAME.Astral_pins = nil
    end
    self.GAME.Astral_pins = self.GAME.Astral_pins or {}
    for k, v in pairs(SMODS.PokerHands) do
        if k ~= 'aij_Royal Flush' then
            self.GAME.Astral_pins[k] = self.GAME.Astral_pins[k] or {}
        end
    end
end
'''
