[manifest]
version = "1.0.0"
dump_lua = true
priority = 214748364

# Moon Cards (1/2)
# Prevent blue seals from generating moons
# Card:get_end_of_round_effect()
[[patches]]
[patches.regex]
target = "card.lua"
pattern = '''(?<indent>[\t ]*)if v.config.hand_type == G.GAME.last_hand_played (?<post>.*)'''
position = "at"
line_prepend = '$indent'
payload = '''if v.config.hand_type == G.GAME.last_hand_played and not v.config.moon $post'''



# Block planets / moons of the same hand type from appearing at once (1/2)
# Also used by Astrologer, since Astrologer changes planet card after used jokers are removed from the pool. So an unused planet could be picked and converted into a used planet
# get_current_pool()
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''pool_opts = pool_opts or {}'''
position = "after"
match_indent = true
payload = '''
local aij_manual_block = false
if v.set == 'Planet' and (All_in_Jest.config.moons_blocking or next(SMODS.find_card('j_aij_astrologer'))) and not G.GAME.used_jokers[v.key] then
    for k, other in pairs(G.P_CENTER_POOLS.Planet) do
        if other.config.hand_type == v.config.hand_type and G.GAME.used_jokers[other.key] then
            aij_manual_block = true
            G.GAME.used_jokers[v.key] = true
            break
        end
    end
end
'''

# Block planets / moons of the same hand type from appearing at once (2/2)
# get_current_pool()
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if v.no_pool_flag and G.GAME.pool_flags[v.no_pool_flag] then add = nil end'''
position = "before"
match_indent = true
payload = '''
if aij_manual_block then
    G.GAME.used_jokers[v.key] = nil
end
'''
