[manifest]
version = "1.0.0"
dump_lua = true
priority = 214748364


# Seal Edition Calculation
# SMODS.trigger_effects()
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "for _, key in ipairs({'jokers', 'retriggers'}) do"
position = "before"
payload = '''
for _, key in ipairs({'aij_seal_edition'}) do
    SMODS.calculate_effect_table_key(effect_table, key, card, ret)
end
'''
match_indent = true

# Correctly load cards with seal editions
# Card:load()
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'self.config.center = G.P_CENTERS[self.config.center_key]'
position = "after"
match_indent = true
payload = '''
if cardTable.aij_seal_edition then
    self.aij_seal_edition = cardTable.aij_seal_edition
end
'''

# Copy seal editions
# copy_card()
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if not strip_edition then"
position = "before"
match_indent = true
payload = '''
--Seal edition copys (mainly for deck view)
new_card:All_in_Jest_set_seal_edition(other.aij_seal_edition or {}, nil, true)
for k,v in pairs(other.aij_seal_edition or {}) do
    if type(v) == 'table' then
        new_card.aij_seal_edition[k] = copy_table(v)
    else
        new_card.aij_seal_edition[k] = v
    end
end
'''

# Add tootip for seal editions
# generate_card_ui()
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if _c.set == 'Other' then"
position = "before"
match_indent = true
payload = '''
if _c.is_seal_edition then
    desc_nodes.name = ' '..localize{type = 'name_text', key = _c.edition_key, set = 'Edition'}..' '..localize{type = 'name_text', key = _c.seal_key, set = 'Other'}..' '
end
if card and card.aij_seal_edition and card.seal then
    local ed_key = card.aij_seal_edition.key
    if G.P_CENTERS[ed_key] and G.P_CENTERS[ed_key].set == 'Edition' then
        local t = {key = ed_key, set = 'Edition', config = {}}
        if ed_key == 'e_aij_stellar' then
            t = {key = 'e_aij_stellar_alt', set = 'Edition', config = card.aij_seal_edition}
        end
        if localize(SMODS.merge_defaults(t, {type = 'name_text'})) == 'ERROR' then t.key = ed_key end
        t.is_seal_edition = true
        t.seal_key = string.lower(G.P_SEALS[card.seal].key)..'_seal'
        t.edition_key = ed_key
        info_queue[#info_queue + 1] = t
        local fake_card = {edition = card.aij_seal_edition}
        if G.P_CENTERS[ed_key].loc_vars and type(G.P_CENTERS[ed_key].loc_vars) == 'function' then
            local res = G.P_CENTERS[ed_key]:loc_vars(info_queue, fake_card) or {}
            t.vars = res.vars
            t.key = res.key or t.key
            t.set = res.set or t.set
        end
    end
end
'''