[manifest]
version = "1.0.0"
dump_lua = true
priority = 214748364

# Hook SMODS.get_enhancements
# This could be a function hook, except it would be inefficient,
# SMODS uses a cache
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''SMODS.enh_cache:write(card, enhancements)'''
position = 'before'
match_indent = true
payload = '''
-- Prevent Astral Pins from having themselves as enhancement
-- in SMODS.get_enhancements()
if card.config.center.is_pin then
    enhancements[card.config.center.key] = nil
end
All_in_Jest.get_enhancements_hook(card, extra_only, enhancements)
'''